# Reusable Docker Build and Push workflow
# Purpose:
#   Build and optionally push container images for this repository using
#   docker/build-push-action. Supports multi-arch builds, SBOM, provenance,
#   GitHub Actions cache, and attestation.
#
# Inputs:
#   dockerfile_path  - Path to the Dockerfile (default: "Dockerfile")
#   build_context    - Docker build context (default: ".")
#   registry         - Container registry URL (default: "ghcr.io")
#   platforms        - Target platforms, comma-separated (default: "linux/amd64,linux/arm64")
#   push_enabled     - Enable pushing to registry (default: true)
#   custom_tags      - Additional image tags, comma-separated
#   semantic_version - Semantic version from release job (e.g., 1.2.3)
#
# Outputs:
#   image_tags   - Generated image tags
#   image_digest - Digest of the built image
#
# Required secrets / permissions:
#   - GITHUB_TOKEN (used for registry login and package write)
#   - Workflow permissions: id-token: write for attestation/OIDC if used
#
# Example call from another workflow:
#   uses: ./.github/workflows/docker-build-reusable.yml
#   with:
#     dockerfile_path: ./Dockerfile
#     build_context: .
#     registry: ghcr.io
#     semantic_version: 1.2.3

name: Internal - Docker Build

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
      build_context:
        required: false
        type: string
        default: '.'
      platforms:
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'
      semantic_version:
        required: false
        type: string
        default: ''
    outputs:
      image_tags:
        value: ${{ jobs.build.outputs.tags }}
      image_digest:
        value: ${{ jobs.build.outputs.digest }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          if [ -f "${{ inputs.dockerfile_path }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ Dockerfile found"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "⏭️ No Dockerfile, skipping"
          fi

  build:
    needs: check
    if: needs.check.outputs.exists == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ inputs.semantic_version }},enable=${{ inputs.semantic_version != '' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.semantic_version }},enable=${{ inputs.semantic_version != '' }}
            type=semver,pattern={{major}},value=${{ inputs.semantic_version }},enable=${{ inputs.semantic_version != '' }}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.platforms }}
          provenance: true
          sbom: true

      - name: Attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
