name: Internal - Semantic Release

on:
  workflow_call:
    inputs:
      dry_run:
        required: false
        type: boolean
        default: false
      branches:
        required: false
        type: string
        default: '["main"]'
    outputs:
      new_release_published:
        value: ${{ jobs.release.outputs.new_release_published }}
      new_release_version:
        value: ${{ jobs.release.outputs.new_release_version }}
      new_release_git_tag:
        value: ${{ jobs.release.outputs.new_release_git_tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_git_tag: ${{ steps.semantic.outputs.new_release_git_tag }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install semantic-release
        run: |
          npm install -g \
            semantic-release@23 \
            @semantic-release/git@10 \
            @semantic-release/changelog@6 \
            @semantic-release/github@10 \
            @semantic-release/commit-analyzer@12 \
            @semantic-release/release-notes-generator@13 \
            conventional-changelog-conventionalcommits@7

      - name: Create config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ${{ inputs.branches }},
            "plugins": [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits",
                "releaseRules": [
                  { "type": "feat", "release": "minor" },
                  { "type": "fix", "release": "patch" },
                  { "type": "perf", "release": "patch" },
                  { "breaking": true, "release": "major" }
                ]
              }],
              ["@semantic-release/release-notes-generator", {
                "preset": "conventionalcommits"
              }],
              ["@semantic-release/changelog", {
                "changelogFile": "CHANGELOG.md"
              }],
              "@semantic-release/github",
              ["@semantic-release/git", {
                "assets": ["CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }]
            ]
          }
          EOF

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
